name: Deploy to CH2 and Standalone Runtime

on:
  push:
    branches: [ master ]

        
jobs:         
  build:
    runs-on: ubuntu-latest
    outputs:
      revision: ${{ steps.set-version.outputs.revision }}
      
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17  
      
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "${{ secrets.MAVEN_SETTINGS_BASE64 }}" | base64 --decode > ~/.m2/settings.xml
          
           
      - name: Generate exchange version dynamically
        id: set-version
        run: |
          VERSION=1.0.${{ github.run_number }}
          echo "revision=$VERSION" >> $GITHUB_OUTPUT       
      
      - name: Publish to Exchange
        run: |
          mvn deploy --settings ~/.m2/settings.xml -DskipMunitTests \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
          -Drevision=${{ steps.set-version.outputs.revision }}         
          

  ch2deploy_dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "${{ secrets.MAVEN_SETTINGS_BASE64 }}" | base64 --decode > ~/.m2/settings.xml  

      - name: Deploy to CloudHub 2.0 - Dev
        run: |
          mvn deploy --settings ~/.m2/settings.xml -DskipMunitTests -DmuleDeploy \
          -Pdev \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
          -Drevision=${{ needs.build.outputs.revision }} \
          -DskipExistingAppCheck=true
  
  ch2deploy_qa:
    needs: [build, ch2deploy_dev]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "${{ secrets.MAVEN_SETTINGS_BASE64 }}" | base64 --decode > ~/.m2/settings.xml         

      - name: Deploy to CloudHub 2.0 - Test
        run: |
          mvn deploy --settings ~/.m2/settings.xml -DskipMunitTests -DmuleDeploy \
          -Pqa \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
          -Drevision=${{ needs.build.outputs.revision }} \
          -DskipExistingAppCheck=true
                                                              
  onprem_deploy:
    needs: ch2deploy_qa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "${{ secrets.MAVEN_SETTINGS_BASE64 }}" | base64 --decode > ~/.m2/settings.xml  
          
      - name: Deploy to Standalone Runtime - Dev
        run: |
          mvn clean deploy -Ponprem --settings ~/.m2/settings.xml -DskipMunitTests -DmuleDeploy